name: Lint Codebase

on:
  pull_request:
    paths:
      - '**.swift'

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftLint
        uses: GetAutomaApp/opensource-actions/swiftlint@main
